# Generated by Django 3.1 on 2020-08-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True, null=True)),
                ('position', models.CharField(max_length=128)),
                ('dob', models.DateField()),
                ('vertical', models.CharField(max_length=128)),
                ('department', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
